version: "3"
services:
  app:
    build: .
    ports:
      - 8000:80
    restart: always
    volumes:
      - .:/var/www/html
#    links:
#      - mysql
#    working_dir: /var/www/html/my_project
#  mysql:
#    image: mysql:5.7.28
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - 33063:3306
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=123
#      - MYSQL_DATABASE=study_php